### ISSUE TITLE
Releases mapping in README

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-release-tool#12]
Hello,

In the README file, I think we also need to show information about releases. For example, in the BO we could have something like

| Kuzzle | BO | URL |
|-----------|------|-------|
| 1.x | 2.x | http://kuzzle-backoffice-2.netlify.com (**preview**) |
| 1.1 | 2.1 | http://kuzzle-backoffice.netlify.com  |
| 1.0.0-RC.9 | 2.0 | x |

And we probably need the same thing for SDKs

**Comment by scottinet** [comment]
Won't do: new versions appear in the repo's tags page.
