### ISSUE TITLE
Modularisation of releasing tool

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle-release-tool#23]
Today we have a flat flow releasing process.

We will have to do different actions on different projects at different moments.
- if a `package.json` file is present, check if there is no published dependencies
- if there is a change labeled with `need-documentation` check on github if there is a documentation available
- ... 

We have to check how to allow to customize this flow. (plugin system ?)

**Comment by scottinet** [comment]
We updated our processes in such a way that this is no longer needed.
